[[language]]
name = "python"
auto-format = true
language-servers = [
    "pylsp"
]

#[language-server.pylsp.config.pylsp]
#plugins.ruff.enabled = true

[language-server.pylsp.plugins.ruff]
enabled = true
formatEnabled = true
lineLength = 100
